### ISSUE TITLE
convert from PropertySet to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/optics-lab#7]
PropertySet is deprecated and should be replaced by Property, see phetsims/axon#102. Since this sim hasn't published yet, this should be done before RC testing and publishing.

**Comment by veillette** [comment]
We should address all the assertions that are currently being triggered before performing the conversion to Property ( #9, #11, #13, #14)

**Comment by veillette** [comment]
I forgot to tag this commit: https://github.com/phetsims/optics-lab/commit/6c3030f100f2a7792bda8508d8b0542a07e7d28c

**Comment by veillette** [comment]
I addressed the assertions, except for #9. Since I was able to reproduce how to trigger this assertion, I was able to work around it and do the conversion to PropertySet.

The simulation is currently lacking a reset all button but reset functions were added to reset the properties.

The reset issue is tracked in #20

**Comment by veillette** [comment]
Work done. Closing
